# -*- coding: utf-8 -*-
"""
  functions_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 8

import numpy as np
from openmdao.api import ExplicitComponent

class FunctionsBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Functions discipline """

    def setup(self):
        self.add_input('x', val=2.0, desc='')
        self.add_input('y1', val=np.ones((1,)), desc='')
        self.add_input('y2', val=np.ones((1,)), desc='')
        self.add_input('z', val=[5.0, 2.0], desc='')

        self.add_output('f', val=np.ones((1,)), desc='')

        self.add_output('g1', val=np.ones((1,)), desc='')

        self.add_output('g2', val=np.ones((1,)), desc='')


        