# -*- coding: utf-8 -*-
"""
  nested_sellar.py generated by WhatsOpt 1.10.4
"""
from optparse import OptionParser
from openmdao.api import Problem
from openmdao.api import NonlinearBlockGS, ScipyKrylov
# from openmdao_extensions.reckless_nonlinear_block_gs import RecklessNonlinearBlockGS
from nested_sellar_base import NestedSellarBase, NestedSellarFactoryBase

class NestedSellar(NestedSellarBase):
    """ An OpenMDAO component to encapsulate NestedSellar analysis """
    def __init__(self, **kwargs):
        super(NestedSellar, self).__init__(**kwargs)

        # Example of manual solver adjusments (imports should be adjusted accordingly)
        # self.nonlinear_solver = NewtonSolver() 
        # self.nonlinear_solver.options['maxiter'] = 20
        # self.linear_solver = DirectSolver()

    def setup(self):
        super(NestedSellar, self).setup()


class NestedSellarFactory(NestedSellarFactoryBase):
    """ A factory to create disciplines of NestedSellar analysis """
    pass

if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("-n", "--no-n2", action="store_false", dest='n2_view', default=True, 
                      help="display N2 openmdao viewer")
    (options, args) = parser.parse_args()

    problem = Problem()
    problem.model = NestedSellar()

    problem.setup()
    problem.final_setup()
    
    if options.n2_view:
        from openmdao.visualization.n2_viewer.n2_viewer import n2
        n2(problem)
