# -*- coding: utf-8 -*-
"""
  sellar_conversions.py generated by WhatsOpt. 
"""
import numpy as np
from .sellar.ttypes import *


# Disc1 
def to_openmdao_disc1_inputs(ins, inputs={}):
    
    inputs['x'] = np.array(ins.x)
    inputs['y2'] = np.array(ins.y2)
    inputs['z'] = np.array(ins.z)
    return inputs

def to_thrift_disc1_input(inputs):
    ins = Disc1Input()
    
    
    ins.x = inputs['x'].tolist()
    
    
    ins.y2 = inputs['y2'].tolist()
    
    
    ins.z = inputs['z'].tolist()
    
    return ins

def to_openmdao_disc1_outputs(output, outputs={}):
    
    outputs['y1'] = np.array(output.y1)
    return outputs

def to_thrift_disc1_output(outputs):
    output = Disc1Output()
    
    
    output.y1 = outputs['y1'].tolist()
    
    return output

# Disc2 
def to_openmdao_disc2_inputs(ins, inputs={}):
    
    inputs['y1'] = np.array(ins.y1)
    inputs['z'] = np.array(ins.z)
    return inputs

def to_thrift_disc2_input(inputs):
    ins = Disc2Input()
    
    
    ins.y1 = inputs['y1'].tolist()
    
    
    ins.z = inputs['z'].tolist()
    
    return ins

def to_openmdao_disc2_outputs(output, outputs={}):
    
    outputs['y2'] = np.array(output.y2)
    return outputs

def to_thrift_disc2_output(outputs):
    output = Disc2Output()
    
    
    output.y2 = outputs['y2'].tolist()
    
    return output

# Functions 
def to_openmdao_functions_inputs(ins, inputs={}):
    
    inputs['x'] = np.array(ins.x)
    inputs['y1'] = np.array(ins.y1)
    inputs['y2'] = np.array(ins.y2)
    inputs['z'] = np.array(ins.z)
    return inputs

def to_thrift_functions_input(inputs):
    ins = FunctionsInput()
    
    
    ins.x = inputs['x'].tolist()
    
    
    ins.y1 = inputs['y1'].tolist()
    
    
    ins.y2 = inputs['y2'].tolist()
    
    
    ins.z = inputs['z'].tolist()
    
    return ins

def to_openmdao_functions_outputs(output, outputs={}):
    
    outputs['f'] = np.array(output.f)
    outputs['g1'] = np.array(output.g1)
    outputs['g2'] = np.array(output.g2)
    return outputs

def to_thrift_functions_output(outputs):
    output = FunctionsOutput()
    
    
    output.f = outputs['f'].tolist()
    
    
    output.g1 = outputs['g1'].tolist()
    
    
    output.g2 = outputs['g2'].tolist()
    
    return output

