# -*- coding: utf-8 -*-
/*
  analysis.thrift generated by WhatsOpt. 
*/
namespace py sellar_optim

typedef double Float
typedef i32 Integer
typedef list<Float> Vector
typedef list<Integer> IVector
typedef list<Vector> Matrix
typedef list<IVector> IMatrix
typedef list<Matrix> Cube
typedef list<IMatrix> ICube
typedef list<Cube> HyperCube
typedef list<ICube> IHyperCube

struct FunctionsInput {
    1: Float x      
    2: Float y1      
    3: Float y2      
    4: Vector z      
}

struct FunctionsOutput {
    1: Float f     
    2: Float g1     
    3: Float g2     
}
struct SellarDisc1Input {
    1: Float x      
    2: Float y2      
    3: Vector z      
}

struct SellarDisc1Output {
    1: Float y1     
}
struct SellarDisc2Input {
    1: Float y1      
    2: Vector z      
}

struct SellarDisc2Output {
    1: Float y2     
}

service SellarOptim {
    FunctionsOutput compute_functions(1:FunctionsInput input)
    SellarDisc1Output compute_sellar_disc1(1:SellarDisc1Input input)
    SellarDisc2Output compute_sellar_disc2(1:SellarDisc2Input input)

    void ping()
    oneway void shutdown()
}