# -*- coding: utf-8 -*-
"""
  sub_analysis_proxy.py generated by WhatsOpt. 
"""

from sellar.sellar_base import SellarBase, SellarFactoryBase



class SellarProxy(SellarBase):
    """ An OpenMDAO component to encapsulate Sellar analysis """
    def __init__(self, thrift_client):
        super(SellarProxy, self).__init__()
        self._thrift_client = thrift_client    
