# -*- coding: utf-8 -*-
"""
  aerodynamics_base.py generated by WhatsOpt 1.10.4
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 3


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class AerodynamicsBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Aerodynamics discipline """

    def __init__(self, **kwargs):
        super(AerodynamicsBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("aerodynamics")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('ESF', val=np.ones((1,)), desc='')
        self.add_input('Theta', val=np.ones((1,)), desc='')
        self.add_input('WT', val=np.ones((1,)), desc='')
        self.add_input('x_aer', val=1.0, desc='')
        self.add_input('z', val=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], desc='')

        self.add_output('D', val=np.ones((1,)), desc='')

        self.add_output('dpdx', val=np.ones((1,)), desc='')

        self.add_output('fin', val=np.ones((1,)), desc='')

        self.add_output('L', val=np.ones((1,)), desc='')


        self.declare_partials('*', '*')

        