# -*- coding: utf-8 -*-
"""
  structure_base.py generated by WhatsOpt 1.10.4
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 3


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class StructureBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Structure discipline """

    def __init__(self, **kwargs):
        super(StructureBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("structure")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('L', val=np.ones((1,)), desc='')
        self.add_input('WE', val=np.ones((1,)), desc='')
        self.add_input('x_str', val=[0.0, 0.0], desc='')
        self.add_input('z', val=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], desc='')

        self.add_output('sigma', val=np.ones((5,)), desc='')

        self.add_output('Theta', val=np.ones((1,)), desc='')

        self.add_output('WF', val=np.ones((1,)), desc='')

        self.add_output('WT', val=np.ones((1,)), desc='')


        self.declare_partials('*', '*')

        