# -*- coding: utf-8 -*-
"""
  run_server.py generated by WhatsOpt. 
"""
#!/usr/bin/env python

from thrift.transport import TSocket
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol
from thrift.server import TServer

from server.mod_branin import ModBranin as ModBraninService
from server.mod_branin_conversions import *
from mod_branin import ModBranin as Factory

class ModBraninHandler:
    server = None

    def __init__(self):
        factory = Factory()
        
        self.mod_branin_function = factory.create_mod_branin_function()
        

    # Admin interface
    def ping(self):
        print("Ping!")

    def shutdown(self):
        print("Shutting down ModBranin server...")
        exit(0)

    # ModBranin interface
    
    def compute_mod_branin_function(self, ins):
        outputs = {}
        inputs = to_openmdao_mod_branin_function_inputs(ins)
        self.mod_branin_function.compute(inputs, outputs)
        return to_thrift_mod_branin_function_output(outputs)
    


handler = ModBraninHandler()
processor = ModBraninService.Processor(handler)
transport = TSocket.TServerSocket('0.0.0.0', port=31400)
tfactory = TTransport.TBufferedTransportFactory()
pfactory = TBinaryProtocol.TBinaryProtocolFactory()

server = handler.server = TServer.TSimpleServer(processor, transport, tfactory, pfactory)

print("Starting ModBranin analysis server...")
server.serve()
print("done!")
