# -*- coding: utf-8 -*-
"""
  run_analysis.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 49

from openmdao.api import Problem
from mod_branin import ModBranin 

pb = Problem(ModBranin())
pb.setup()  

pb.run_model()   
pb.model.list_inputs(print_arrays=False)
pb.model.list_outputs(print_arrays=False)

