# -*- coding: UTF-8 -*-
"""
  sellar.py generated by WhatsOpt. 
"""
from openmdao.api import Problem
from sellar_base import SellarBase
from openmdao.api import view_model
from optparse import OptionParser

class Sellar(SellarBase):
    """ An OpenMDAO base component to encapsulate Sellar MDA """
    pass

if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("-n", "--no-n2", action="store_false", dest='n2_view', default=True, 
                      help="display N2 openmdao viewer")
    (options, args) = parser.parse_args()

    problem = Problem()
    problem.model = Sellar()

    problem.setup()
    problem.final_setup()
    
    if options.n2_view:
        view_model(problem)
    