# -*- coding: utf-8 -*-
/*
  analysis.thrift generated by WhatsOpt. 
*/
namespace py sellar

typedef double Float
typedef i32 Integer
typedef list<Float> Vector
typedef list<Integer> IVector
typedef list<Vector> Matrix
typedef list<IVector> IMatrix
typedef list<Matrix> Cube
typedef list<IMatrix> ICube
typedef list<Cube> HyperCube
typedef list<ICube> IHyperCube

struct Disc1Input {
    1: Vector x      
    2: Vector y2      
    3: Vector z      
}

struct Disc1Output {
    1: Vector y1     
}
struct Disc2Input {
    1: Vector y1      
    2: Vector z      
}

struct Disc2Output {
    1: Vector y2     
}
struct FunctionsInput {
    1: Vector x      
    2: Vector y1      
    3: Vector y2      
    4: Vector z      
}

struct FunctionsOutput {
    1: Vector f     
    2: Vector g1     
    3: Vector g2     
}

service Sellar {
    Disc1Output compute_disc1(1:Disc1Input input)
    Disc2Output compute_disc2(1:Disc2Input input)
    FunctionsOutput compute_functions(1:FunctionsInput input)

    void ping()
    oneway void shutdown()
}