# -*- coding: utf-8 -*-
"""
  sellar_proxy.py generated by WhatsOpt. 
"""
from thrift import Thrift
from thrift.transport import TSocket
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol

from server.sellar import Sellar
from sellar import Sellar as SellarOriginal

from .discipline_proxy import Disc1Proxy

from .discipline_proxy import Disc2Proxy

from .discipline_proxy import FunctionsProxy


class SellarProxy(SellarOriginal):
    
    def __init__(self):
        super(SellarProxy, self).__init__()
        transport = TSocket.TSocket('localhost', 31400)
        transport = TTransport.TBufferedTransport(transport)
        protocol = TBinaryProtocol.TBinaryProtocol(transport)
        self._thrift_client = Sellar.Client(protocol)
        transport.open()

    
    def create_disc1(self):
        return Disc1Proxy(self._thrift_client)
    
    def create_disc2(self):
        return Disc2Proxy(self._thrift_client)
    
    def create_functions(self):
        return FunctionsProxy(self._thrift_client)
    

    def ping(self):
        self._thrift_client.ping()

    def shutdown(self):
        self._thrift_client.shutdown()
    