# -*- coding: utf-8 -*-
"""
  run_server.py generated by WhatsOpt. 
"""
#!/usr/bin/env python

from thrift.transport import TSocket
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol
from thrift.server import TServer

from server.ssbj_mda import SsbjMda as SsbjMdaService
from server.ssbj_mda_conversions import *
from ssbj_mda import SsbjMdaFactory as Factory

class SsbjMdaHandler:
    server = None

    def __init__(self):
        factory = Factory()
        
        self.performance = factory.create_performance()
        
        self.constraints = factory.create_constraints()
        
        self.mda_structure = factory.create_mda_structure()
        
        self.mda_aerodynamics = factory.create_mda_aerodynamics()
        
        self.mda_propulsion = factory.create_mda_propulsion()
        

    # Admin interface
    def ping(self):
        print("Ping!")

    def shutdown(self):
        print("Shutting down SsbjMda server...")
        exit(0)

    # SsbjMda interface
    
    def compute_performance(self, ins):
        outputs = {}
        inputs = to_openmdao_performance_inputs(ins)
        self.performance.compute(inputs, outputs)
        return to_thrift_performance_output(outputs)
    
    def compute_constraints(self, ins):
        outputs = {}
        inputs = to_openmdao_constraints_inputs(ins)
        self.constraints.compute(inputs, outputs)
        return to_thrift_constraints_output(outputs)
    
    def compute_mda_structure(self, ins):
        outputs = {}
        inputs = to_openmdao_mda_structure_inputs(ins)
        self.mda_structure.compute(inputs, outputs)
        return to_thrift_mda_structure_output(outputs)
    
    def compute_mda_aerodynamics(self, ins):
        outputs = {}
        inputs = to_openmdao_mda_aerodynamics_inputs(ins)
        self.mda_aerodynamics.compute(inputs, outputs)
        return to_thrift_mda_aerodynamics_output(outputs)
    
    def compute_mda_propulsion(self, ins):
        outputs = {}
        inputs = to_openmdao_mda_propulsion_inputs(ins)
        self.mda_propulsion.compute(inputs, outputs)
        return to_thrift_mda_propulsion_output(outputs)
    


handler = SsbjMdaHandler()
processor = SsbjMdaService.Processor(handler)
transport = TSocket.TServerSocket('0.0.0.0', port=31400)
tfactory = TTransport.TBufferedTransportFactory()
pfactory = TBinaryProtocol.TBinaryProtocolFactory()

server = handler.server = TServer.TSimpleServer(processor, transport, tfactory, pfactory)

print("Starting SsbjMda analysis server...")
server.serve()
print("done!")
