# -*- coding: utf-8 -*-
"""
  run_analysis.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 99

from openmdao.api import Problem

# Use ssbj_openmdao as a module (required so that next from/import line work)
import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), "ssbj_openmdao"))

from ssbj_mda import SsbjMda 

pb = Problem(SsbjMda())
pb.setup()  

pb.run_model()   
pb.model.list_inputs(print_arrays=False)
pb.model.list_outputs(print_arrays=False)

