# -*- coding: utf-8 -*-
/*
  analysis.thrift generated by WhatsOpt. 
*/
namespace py mod_branin

typedef double Float
typedef i32 Integer
typedef list<Float> Vector
typedef list<Integer> IVector
typedef list<Vector> Matrix
typedef list<IVector> IMatrix
typedef list<Matrix> Cube
typedef list<IMatrix> ICube
typedef list<Cube> HyperCube
typedef list<ICube> IHyperCube

struct ModBraninFunctionInput {
    1: Float x1      
    2: Float x2      
}

struct ModBraninFunctionOutput {
    1: Float f     
    2: Float g     
}

service ModBranin {
    ModBraninFunctionOutput compute_mod_branin_function(1:ModBraninFunctionInput input)

    void ping()
    oneway void shutdown()
}