# -*- coding: utf-8 -*-
"""
  mod_branin_conversions.py generated by WhatsOpt. 
"""
import numpy as np
from .mod_branin.ttypes import *


# ModBraninFunction 
def to_openmdao_mod_branin_function_inputs(ins, inputs={}):
    
    inputs['x1'] = np.array(ins.x1)
    inputs['x2'] = np.array(ins.x2)
    return inputs

def to_thrift_mod_branin_function_input(inputs):
    ins = ModBraninFunctionInput()
    
    
    ins.x1 = float(inputs['x1'])
    
    
    ins.x2 = float(inputs['x2'])
    
    return ins

def to_openmdao_mod_branin_function_outputs(output, outputs={}):
    
    outputs['f'] = np.array(output.f)
    outputs['g'] = np.array(output.g)
    return outputs

def to_thrift_mod_branin_function_output(outputs):
    output = ModBraninFunctionOutput()
    
    
    output.f = float(outputs['f'])
    
    
    output.g = float(outputs['g'])
    
    return output

