# -*- coding: utf-8 -*-
"""
  sellar_optim_proxy.py generated by WhatsOpt. 
"""
from thrift import Thrift
from thrift.transport import TSocket
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol

from server.sellar_optim import SellarOptim
from sellar_optim_base import SellarOptimBase

from .discipline_proxy import FunctionsProxy

from .discipline_proxy import Disc1Proxy

from .discipline_proxy import Disc2Proxy


class SellarOptimProxy(SellarOptimBase):
    
    def __init__(self):
        super(SellarOptimProxy, self).__init__()
        transport = TSocket.TSocket('localhost', 31400)
        transport = TTransport.TBufferedTransport(transport)
        protocol = TBinaryProtocol.TBinaryProtocol(transport)
        self._thrift_client = SellarOptim.Client(protocol)
        transport.open()

    
    def create_functions(self):
        return FunctionsProxy(self._thrift_client)
    
    def create_disc1(self):
        return Disc1Proxy(self._thrift_client)
    
    def create_disc2(self):
        return Disc2Proxy(self._thrift_client)
    

    def ping(self):
        self._thrift_client.ping()

    def shutdown(self):
        self._thrift_client.shutdown()
    