# -*- coding: utf-8 -*-
"""
  mod_branin.py generated by WhatsOpt. 
"""

from openmdao.api import Problem
from mod_branin_base import ModBraninBase
from openmdao.api import view_model
from optparse import OptionParser

class ModBranin(ModBraninBase):
    """ An OpenMDAO base component to encapsulate ModBranin MDA """
    pass

if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("-n", "--no-n2", action="store_false", dest='n2_view', default=True, 
                      help="display N2 openmdao viewer")
    (options, args) = parser.parse_args()

    problem = Problem()
    problem.model = ModBranin()

    problem.setup()
    problem.final_setup()
    
    if options.n2_view:
        view_model(problem)
    