# -*- coding: utf-8 -*-
"""
  run_optimization.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 49

import sys
import numpy as np
# import matplotlib
# matplotlib.use('Agg')
import matplotlib.pyplot as plt
from openmdao.api import Problem, SqliteRecorder, CaseReader, ScipyOptimizeDriver #, pyOptSparseDriver
from mod_branin import ModBranin 

from whatsopt.oneramdao_driver import OneramdaoOptimizerDriver

from optparse import OptionParser
parser = OptionParser()
parser.add_option("-b", "--batch",
                  action="store_true", dest="batch", default=False,
                  help="do not plot anything")
(options, args) = parser.parse_args()

pb = Problem(ModBranin())

pb.driver = ScipyOptimizeDriver()
pb.driver.options['optimizer'] = 'SLSQP'


pb.driver.options['tol'] = 1.0e-06

pb.driver.options['maxiter'] = 100

pb.driver.options['disp'] = True
#pb.driver.options['debug_print'] = ['desvars','ln_cons','nl_cons','objs', 'totals']
pb.driver.options['debug_print'] = []

case_recorder_filename = 'mod_branin_optimization.sqlite'
print(case_recorder_filename)        
recorder = SqliteRecorder(case_recorder_filename)
pb.driver.add_recorder(recorder)
pb.model.add_recorder(recorder)
pb.model.nonlinear_solver.add_recorder(recorder)

# Derivatives are compute via finite-difference method
# to be commnented out if partial derivatives are declared
pb.model.approx_totals(method='fd', step=1e-6, form='central')

pb.model.add_design_var('x1', lower=-5, upper=10)
pb.model.add_design_var('x2', lower=0, upper=15)

pb.model.add_objective('f')


pb.model.add_constraint('g', upper=0.)

pb.setup()  
pb.run_driver()      

if options.batch:
    exit(0)  
reader = CaseReader(case_recorder_filename)
cases = reader.system_cases.list_cases()
n = len(cases)
data = {'inputs': {}, 'outputs': {} }

data['inputs']['x1'] = np.zeros((n,)+(1,))
data['inputs']['x2'] = np.zeros((n,)+(1,))

data['outputs']['f'] = np.zeros((n,)+(1,))
data['outputs']['g'] = np.zeros((n,)+(1,))

for i, case_id in enumerate(cases):
    case = reader.system_cases.get_case(case_id)
    data['inputs']['x1'][i,:] = case.inputs['x1']
    data['inputs']['x2'][i,:] = case.inputs['x2']
    data['outputs']['f'][i,:] = case.outputs['f']
    data['outputs']['g'][i,:] = case.outputs['g']
      
