# -*- coding: utf-8 -*-
"""
  mda.py generated by WhatsOpt. 
"""
from optparse import OptionParser
from openmdao.api import Problem
from openmdao.api import NonlinearBlockGS, ScipyKrylov
from openmdao.api import view_model
from openmdao_extensions.reckless_nonlinear_block_gs import RecklessNonlinearBlockGS
from mda.mda_base import MdaBase, MdaFactoryBase

from .structure import Structure
from .aerodynamics import Aerodynamics
from .propulsion import Propulsion

class Mda(MdaBase):
    """ An OpenMDAO component to encapsulate Mda analysis """
    def __init__(self, scalers):
        super(Mda, self).__init__()
        self.scalers = scalers

    def setup(self):
        super(Mda, self).setup()
        
        self.nonlinear_solver = NonlinearBlockGS() 
        self.linear_solver = ScipyKrylov()

    def create_structure(self):
    	return Structure(self.scalers)
    
    def create_aerodynamics(self):
    	return Aerodynamics(self.scalers)
    
    def create_propulsion(self):
    	return Propulsion(self.scalers)