# -*- coding: utf-8 -*-
"""
  aerodynamics_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 124

import numpy as np
from openmdao.api import ExplicitComponent

class AerodynamicsBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Aerodynamics discipline """

    
    def setup(self):
		
        self.add_input('ESF', val=np.ones((1,)), desc='')
        self.add_input('Theta', val=np.ones((1,)), desc='')
        self.add_input('WT', val=np.ones((1,)), desc='')
        self.add_input('x_aer', val=np.ones((1,)), desc='')
        self.add_input('z', val=np.ones((6,)), desc='')
		
        self.add_output('dpdx', val=np.ones((1,)), desc='')
        self.add_output('D', val=np.ones((1,)), desc='')
        self.add_output('L', val=np.ones((1,)), desc='')
        self.add_output('fin', val=np.ones((1,)), desc='')
	

        