# -*- coding: utf-8 -*-
"""
  performance_base.py generated by WhatsOpt 1.10.4
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: https://ether.onera.fr/whatsopt
# analysis_id: 2


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class PerformanceBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Performance discipline """

    def __init__(self, **kwargs):
        super(PerformanceBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("performance")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('fin', val=np.ones((1,)), desc='')
        self.add_input('SFC', val=np.ones((1,)), desc='')
        self.add_input('WF', val=np.ones((1,)), desc='')
        self.add_input('WT', val=np.ones((1,)), desc='')
        self.add_input('z', val=[1.0, 1.0, 1.0, 1.0, 1.0, 1.0], desc='')

        self.add_output('R', val=np.ones((1,)), desc='')



        