# -*- coding: utf-8 -*-
"""
  run_parameters_init.py generated by WhatsOpt 1.10.4
"""
import numpy as np
from numpy import nan

def initialize(mda):

    mda['x_aer'] = 1.0
    mda['x_pro'] = 1.0
    mda['x_str'] = [1.0, 1.0]
    mda['z'] = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]



if __name__ == "__main__":
    from tabulate import tabulate

    mda = {}
    initialize(mda)
    headers = ["parameter", "value"]
    data = [[k, mda[k]] for k in mda]
    print(tabulate(data, headers))