# -*- coding: utf-8 -*-
"""
  run_analysis.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 2

from openmdao.api import Problem
from ssbj_mda import SsbjMda 
from ssbj_openmdao.ssbj_mda import init_ssbj_mda 

scalers = init_ssbj_mda()
pb = Problem(SsbjMda(scalers))
pb.setup()  

pb.run_model()   
pb.model.list_inputs(print_arrays=False)
pb.model.list_outputs(print_arrays=False)

