# -*- coding: utf-8 -*-
"""
  run_analysis.py generated by WhatsOpt 1.10.4
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 2

from openmdao.api import Problem
from run_parameters_init import initialize
from ssbj_mda import SsbjMda 

pb = Problem(SsbjMda())
pb.setup()  

initialize(pb)

pb.run_model()   
pb.model.list_inputs(print_arrays=False)
pb.model.list_outputs(print_arrays=False)

