# -*- coding: utf-8 -*-
"""
  propulsion_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 124

import numpy as np
from openmdao.api import ExplicitComponent

class PropulsionBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Propulsion discipline """

    
    def setup(self):
		
        self.add_input('D', val=np.ones((1,)), desc='')
        self.add_input('x_pro', val=np.ones((1,)), desc='')
        self.add_input('z', val=np.ones((6,)), desc='')
		
        self.add_output('DT', val=np.ones((1,)), desc='')
        self.add_output('ESF', val=np.ones((1,)), desc='')
        self.add_output('Temp', val=np.ones((1,)), desc='')
        self.add_output('WE', val=np.ones((1,)), desc='')
        self.add_output('SFC', val=np.ones((1,)), desc='')
	

        