# -*- coding: utf-8 -*-
"""
  run_analysis.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 124

from openmdao.api import Problem
from ssbj import Ssbj 

pb = Problem(Ssbj())
pb.setup()  

pb.run_model()   
pb.model.list_inputs(print_arrays=True)
pb.model.list_outputs(print_arrays=True)

